version: '3.7'

services:
  ws-demon:
    image: ws-demon
    build:
      context: .
      dockerfile: ws-demon.Dockerfile
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6378
    depends_on:
      - redis

  morphey:
    image: morphey
    build:
      context: .
      dockerfile: morphey.Dockerfile
    volumes:
      - .:/wd
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MONGO_URL=mongo
      - MONGO_PORT=27017
      - REDIS=redis
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  redis:
    image: redis
    ports:
      - "6378:6379"

  mongo:
    image: mongo
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: mongo_username
    #      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
