version: '3.7'

services:

  bifrost-bridge:
    image: bifrost-bridge
    build:
      context: ./BifrostBridge
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis
    depends_on:
      - redis

  morphey:
    image: morphey
    build:
      context: ./Morphey
      dockerfile: Dockerfile
    command: "uvicorn morphey.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./Morphey:/morphey
    environment:
      - REDIS_URL=redis
    ports:
      - "8000:8000"
    depends_on:
      - redis

  morphey_db:
    image: postgres:12
    container_name: morphey_db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data-morphey:/var/lib/postgresql/data
      - ./Morphey/init_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"


  redis:
    image: redis
    ports:
      - "6379:6379"

#  mongo:
#    image: mongo
#    #    environment:
#    #      MONGO_INITDB_ROOT_USERNAME: mongo_username
#    #      MONGO_INITDB_ROOT_PASSWORD: mongo_password
#    ports:
#      - "27017:27017"

volumes:
  db-data-morphey:
    driver: local
