version: '3.7'

services:
  ws-demon:
    image: ws-demon
    build:
      context: .
      dockerfile: ws-demon.Dockerfile
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6378
    depends_on:
      - redis

  morphey:
    image: morphey
    build:
      context: .
      dockerfile: morphey.Dockerfile
    ports:
      - "5000:8080"

  redis:
    image: redis
    ports:
      - "6378:6379"